### ISSUE TITLE
Data length different by 1: mirenvelope  (…, 'Gauss', o) -> sig.envelope  (…, 'Gauss', o)

### ISSUE THREAD

**Issue by emoninet2** [olivierlar/miningsuite#10]
The data size of that produced by **mirenvelope(…, 'Gauss', o)** is shorter than **sig.envelope(…, 'Gauss', o)** by 1. 

When tested with ragtime.wav, the size of the data was as follows:

mirenvelope  (…, 'Gauss', o) -> 11517
sig.envelope (…, 'Gauss', o)-> 11518

**Comment by olivierlar** [comment]
Bug found in MiningSuite. Now corrected.
