### ISSUE TITLE
Data length different by 1: mirspectrum(…, ‘Max’, mi) -> sig.spectrum(…, ‘Max’, mi)

### ISSUE THREAD

**Issue by emoninet2** [olivierlar/miningsuite#11]
The data size of that produced by **mirspectrum(…, ‘Max’, mi)** is more than **sig.spectrum(…, ‘Max’, mi)** by 1.

When tested with ragtime.wav, the size of the data was as follows:

mirspectrum(…, ‘Max’, mi) -> 596
sig.spectrum(…, ‘Max’, mi) -> 595

**Comment by olivierlar** [comment]
Bug found in MIRtoolbox. Now corrected.
